### ISSUE TITLE
Show Some Events at incorrect time slots in 'Week', '3 Days' and '1 Day' calendar view

### ISSUE THREAD

**Issue by ejazahmad47** [nibdo/calend#12]
The calendar show the event block at incorrect time slots for some events. It show the events blocks at correct position for other events.
in the live demo, the props shows correct start and end time. the event card also shows the start and end time correct.
![screenshot from demo page](https://user-images.githubusercontent.com/62111605/144423601-1f74d972-19ba-492b-82f9-8ed7943ebfab.png)
but shows the event block at incorrect rows [i.e starting from around 9:30 to 11:30 when it should start from 13th row and end on 15.5th row ]

![screenshot from local app/setup](https://user-images.githubusercontent.com/62111605/144424708-694839b7-e43d-4ec9-b4d1-fc49600316de.png)

**Comment by nibdo** [comment]
Thank you very much. Should be fixed in version 0.0.3
