### ISSUE TITLE
Today button doesn't work properly

### ISSUE THREAD

**Issue by Eragaus** [nibdo/calend#13]
When clicking "Today" button on Day and "3 Days" views, wrong days are displayed.

![image](https://user-images.githubusercontent.com/44021247/144435492-09c426c9-a20e-497c-89c3-fafec651ae0d.png)
![image](https://user-images.githubusercontent.com/44021247/144435527-ae0421ac-6d57-4d60-91a3-76c14cbd13ea.png)

**Comment by nibdo** [comment]
Fixed in version 0.0.3

**Comment by nibdo** [comment]
And thank you :)
