### ISSUE TITLE
Broken in version 0.0.2 and 0.0.3

### ISSUE THREAD

**Issue by ejazahmad47** [nibdo/calend#23]
Everything seems broken when upgraded to in V0.0.3 [also in V0.0.2]
Using in app created with CRA.
![image](https://user-images.githubusercontent.com/62111605/144675165-31ed4542-a60d-471c-9eb9-e4571c7086c6.png)

**Comment by nibdo** [comment]
Hello, please try to import also css file.

```
import 'calend/styles/index.css';
```

I had to separate it to support also next.js.

Please, let me know, if you still have problem after importing it.

Thank you

**Comment by ejazahmad47** [comment]
OK.
Thanks a lot
