### ISSUE TITLE
Add Storybook

### ISSUE THREAD

**Issue by bruceharrison1984** [nibdo/calend#36]
Would you be interested in adding Storybook to this to aid with UX development? I've found it tremendously helpful for frontend work in multiple projects.

I'd be willing to take on the implementation, I figured I ask if it's something you're interested in before putting forth the effort.

Great job so far 👍

**Comment by nibdo** [comment]
It would be great, I think it could also help to attract more contributors in the future. Thank you very much

**Comment by bruceharrison1984** [comment]
no problem. I'll get it in working order with a few components and submit a PR. We can add the additional components as time goes on.
